### ISSUE TITLE
createVerifier won't verify properly with RS256

### ISSUE THREAD

**Issue by kavishkagihan** [nearform/fast-jwt#414]
I am trying to implement JWT logic to a web application using `fast-jwt`. When I am trying to use the `createVerifier` to verify the token, created with RS256 algorithm, it will always fail no matter what. 

```js
const { createSigner } = require('fast-jwt')
const { createVerifier } = require('fast-jwt')
const fs = require('fs');
const path = require('path');

const publicKeyPath = path.join(__dirname, 'public_key.pem');
const publicKey = fs.readFileSync(publicKeyPath, 'utf8');
const privateKeyPath = path.join(__dirname, 'key');
const privateKey = fs.readFileSync(privateKeyPath, 'utf8');

const payload = { admin: false, name: 'test' };

const signSync = createSigner({ algorithm: 'RS256', key: privateKey});
const token = signSync(payload);

console.log(token);

const verifySync = createVerifier({ key: publicKey });

const dec_payload = verifySync(token);
console.log(dec_payload)
```
This will create the token successfully but will exit when trying to verify the token saying, `The token algorithm is invalid`.

```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsIm5hbWUiOiJ0ZXN0IiwiaWF0IjoxNzAxMTEwOTEzfQ.b6EtkOoixu18QLC7g9eQOCG7on2FomP8vhtkti_slQckrRy7EOTO7bZV2ISK9BvViU-2Bno8VMavqei-ibuB4isGQ_H-Hpw7Vsx0PWHVHPXXbcl3fki4Qa8R-jR8m6LM2I9nsvL0GqfXukzJqDLylWcQnC4icGr7SxBuH0t6sDfi34CUMlh587kJ6MB48NATEpX6vkzOqF2zDCeSqndIHi3cu3Ec5f4iGbdddwpjXCvbJKzAlNOiVEqs8xRyOgvYSC5jAuMPQ36riYQdSdkBYad8JMklaEKS-pFfTc0nrSUab8syUQu4wtD096UkG-rO_4ZQO6NJeR6RoGfLNq3aCw
/app/node_modules/fast-jwt/src/verifier.js:322
      throw cacheSet(cacheContext, e)
      ^

TokenError: The token algorithm is invalid.
    at validateAlgorithmAndSignature (/app/node_modules/fast-jwt/src/verifier.js:148:11)
    at verifyToken (/app/node_modules/fast-jwt/src/verifier.js:201:3)
    at verify (/app/node_modules/fast-jwt/src/verifier.js:318:7)
    at Object.<anonymous> (/app/a.js:20:21)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'FAST_JWT_INVALID_ALGORITHM'
}

Node.js v20.6.0
```

I even tried  specifying the algorithm with,

```js
const verifySync = createVerifier({ key: publicKey, algorithms : ['RS256'] });
```

This gives me a different error saying, `Invalid public key provided for algorithms RS256`

```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsIm5hbWUiOiJ0ZXN0IiwiaWF0IjoxNzAxMTExMjIwfQ.F3S7kYmEPIuJH4yReWXOF8WaAt3NPgXRmOjoec2Fx6PgPu0CQgp7zTASl4eLINsos1vbjXZRWaieqVkFM5RjrNBy4aNZRhc2-pz0S_h2z8TVFENs9qccr36mZDCHg48OFCbgYtLoEO4dXStlqZK4Qd-r0-vmbUf3IDTr3MiSTvHh74kPvEUULVqFAuxcA3QTAWXVyXxXxS4XecvHGsyq-zbo9I700V3l64pWToDoYLDKoRRM_dsxrNyc7BJ93Pn3B3uE0FMHRhmTwRMNt5naJAtr3cWkU6mAGYvZ-xtdnsR5pAa2dbnopC5okh_11hGR-13p2oQG_FN3MI9b4ViF-w
/app/node_modules/fast-jwt/src/verifier.js:30
    throw new TokenError(
    ^

TokenError: Invalid public key provided for algorithms RS256.
    at checkAreCompatibleAlgorithms (/app/node_modules/fast-jwt/src/verifier.js:30:11)
    at createVerifier (/app/node_modules/fast-jwt/src/verifier.js:411:7)
    at Object.<anonymous> (/app/a.js:18:20)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'FAST_JWT_INVALID_KEY'
}

Node.js v20.6.0
```

I used these commands to generate the private and the public keys.

```bash
ssh-keygen -t rsa -b 2048 -m PEM
ssh-keygen -f key.pub -e -m PEM > public_key.pem
```

I have tried using `fast-jwt` version `3.3.2`, `3.3.1` and `3.2.0` with Node versions `20.6.0` and `18.13.0` separately.

**Comment by simoneb** [comment]
Ok thanks for reporting. Would you be so kind as to create a PR? If you don't want to work on the fix, could you at least create a failing test case?

**Comment by kavishkagihan** [comment]
Ok, so I was preparing the test case PR and noticed something. I think the verifier only works for the keys with the headers `-----BEGIN PRIVATE KEY-----` not `-----BEGIN RSA PRIVATE KEY-----`. 
```
# with -----BEGIN PRIVATE KEY-----
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhIjoxLCJpYXQiOjE3MDExODQyODR9.acouVH2kUzUiBW534e-5ysLEuvBj_8U30W8nt4VXgU-avwYPjqPemNWekDKoFYRCDBYju-Ozy9ZnjTNOqrfQOuU6ezdzf1CHIlEj1D1059s_a7iEuEwlRkyXA49e9vyoP7-0Xbiiua17slZHQixJwbDrCyr3B6wezvedTJlxoK6JWv3zrSeQ0P6hTX8DtVxWLQFFwrH-4Mvibbe8oSUPZ6SH1apRH_8PF0XcoDadAtpMCc5agGf8-Y1mKhl82FFpoMa2P8w8sHmqGXDvNvG_t6PBHu-bB8KJ15_99R3C7YUu-bMWpdOs4T0TgSWGviyBUI4bjounbSKYgWUPsWDOgw
{ a: 1, iat: 1701184284 }
```
Then I looked at the commits and found [this](https://github.com/nearform/fast-jwt/commit/15a6e92c9adb39acde41a9b11cec0cbde8ad763b). I thought this was the reason why it didn't work before. But again this was implemented in `v3.3.2` but yet I was testing it in `v3.3.0`.

The key headers were the only thing that was different from my previous test.

**Comment by simoneb** [comment]
I'm not sure what to make of this though. The relevant line is this, which shows that `BEGIN RSA PRIVATE KEY` should be supported. https://github.com/nearform/fast-jwt/commit/15a6e92c9adb39acde41a9b11cec0cbde8ad763b#diff-0ea128c6a526ed8106ac0088dc7d2f94c0d351cc8edd06e24e79b8e5ae4c44a4R28

**Comment by kavishkagihan** [comment]
At this point, I am pretty sure that is the root cause. Just not sure why that would happen.

```bash
┌──(kali__kali)-[~/NEW]
└─$ cat public_key.pem|head
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoxxtE32WroZX5LpgGDQ6
B/LmBBpSAjeQ3ak4t8f1jVCuvfk3RoIGD4nOznGXL1SjKo1exYIpG/EnaWkIXo37
MUlZ/StEmXRWwDZtbrrNJrdj/4qam7527jwjhFESigj95bQ4ndMNqwIfptLt3mm2
t5QdTADy0eHdPdZ7fUuYeGj3BN9fKOnqXZkBRq7C2yB9RoWB0IU7hzHsf11ODbK7
Om4v3dlBm9fiH2dTMbJAxTloeIrMd1OXu/PM5d7qgDjC2TyDmqPgLKGvlfm18LTU
9w+r52qCjAUV0EIK3Ai/ACx4hLfwnb478ZvZfdXDgUhFOrKx92Jp+oejuHqWxPRE
xQIDAQAB
-----END PUBLIC KEY-----


┌──(kali__kali)-[~/NEW]
└─$ node test.js
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhIjoxfQ.dvQmAf8QruptEU1nqwuIHjuE90gftfKNnkOP6i0ErVByjwCij99WLM_6Xbq__OUVjJXwdGYlP71j6-pTrqr6ue8vT6KE-1oPChnc5WyCKZBvpjAuAHG8jF-M899CcHuYUFDQ-UJV0eaRf26ilvngIQE6RMKtdavsFoR3XpiUCXobMJbgZDNvzG5j36M10FccB68C-6Y4F75sid47jfKHKSEYiqJHo6jqSredLVjNNEbVAo3ee4oafLByzEDW6F1-MA3vJZZl522EwXFBv7MnFwvP5QJVOMGxL1R5tmbbOvLKy25v6uAO_VXKPciw4ZCr-BBzeUhuFzSsCauoDZJBhA
{ a: 1 }
```

```bash

┌──(kali__kali)-[~/NEW]
└─$ cat public_key.pem|head
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEApNkAKU4ap1AWiQaeDvPXbLNcd8UElPIK9hYLoTUDD8CCx1YSs8Rr
ACSDlyRtFkwEiplsIvlh8wj/BvkUE9lgQOzO6mcMx7bcqJ2GKaANANBCI/T+r7+D
jeq9jH0pv49eMZzO4Ye5TapVkJEiq4SR/FkLigRVP1lM16IQGqxpjDr4/nHhZ7SF
98F8TC0Suh/F4wgZaN4qrzUaBJJ5ysA3DySLlQkraJpfje5bXFbH3flys8m2SNZf
otRjrMwBrzIvW0kz9qKkbkTUJX2k8hcGkWN6GeoKABx6+v3QXARap740u8lfFYVh
skeeAXg/WhrTIr6EHAIbnJlCWqzLFh9hNQIDAQAB
-----END RSA PUBLIC KEY-----

┌──(kali__kali)-[~/NEW]
└─$ node test.js
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhIjoxfQ.H-e_0TykHbQZfy91O-1CNo4DCIYnCpv2WEP_KPLAfsLKTY3-h27WxO6B2HS1MI23IipAFF5dBHjPTGyUx2GZUDKBqtny9D95DhAQOUYlBK3Z4B3Pg-YBTHWge--Iv0xyNCEHZuSHi7_vDlGl2dEqYH78m88Dh4PPinK22CUbn8WvWhdkGPAFbYmXMSKkypwiazmuAPG_rdltjNxRFBZeNg3-iRqrdFTTG64ZAVHE31v78V_hTyJj-4z8A5mGglMaGrf2WntXpR6vp5SWIFYG3-jrBoeZHpV0rIJQlzhvzobtmuJytMoPQTnUX6yoCc-qgkVCUou1369WUiXFe17gnA
/home/kali/NEW/node_modules/fast-jwt/src/verifier.js:322
      throw cacheSet(cacheContext, e)
      ^

TokenError: The token algorithm is invalid.
```

Also, it seems you had no problems with this before because the `ssh-keygen` commands you have mentioned in the advisory are the same ones I used to create mine (with `-----BEGIN RSA PUBLIC KEY-----` header ).
